<div class='alert alert-warning'>

# JupyterLite warning

- Running the **scikit-plots 0.5.dev0** interactive examples in JupyterLite is experimental and may not always work as expected.
- With high load times especially on low-resource platforms, and the version of scikit-plots might not be in sync with the one you are browsing the documentation for.
- If you encounter any issues, please report them on the [scikit-plots issue tracker](https://github.com/scikit-plots/scikit-plots/issues/new/choose).

```python
# Installing the dependencies first, and then scikit-plots from Anaconda.org.
import piplite; await piplite.install(  # import micropip
   'scikit-plots==0.5.dev0',            # Download scikit-plots *pyodide_20XX_0_wasm32.whl
   index_urls='https://pypi.anaconda.org/scikit-plots-wheels-staging-nightly/simple',
); import sklearn; import scikitplot as sp; sp.show_versions();
 ```

</div>

Obtain a twice resampled array:


In [ ]:
from astropy.stats import bootstrap
import numpy as np
from astropy.utils import NumpyRNGContext
bootarr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
with NumpyRNGContext(1):
    bootresult = bootstrap(bootarr, 2)

bootresult  # doctest: +FLOAT_CMP

array([[6., 9., 0., 6., 1., 1., 2., 8., 7., 0.],
       [3., 5., 6., 3., 5., 3., 5., 8., 8., 0.]])

In [ ]:
bootresult.shape

(2, 10)

Obtain a statistic on the array


In [ ]:
with NumpyRNGContext(1):
    bootresult = bootstrap(bootarr, 2, bootfunc=np.mean)

bootresult  # doctest: +FLOAT_CMP

array([4. , 4.6])

Obtain a statistic with two outputs on the array


In [ ]:
test_statistic = lambda x: (np.sum(x), np.mean(x))
with NumpyRNGContext(1):
    bootresult = bootstrap(bootarr, 3, bootfunc=test_statistic)
bootresult  # doctest: +FLOAT_CMP

array([[40. ,  4. ],
       [46. ,  4.6],
       [35. ,  3.5]])

In [ ]:
bootresult.shape

(3, 2)

Obtain a statistic with two outputs on the array, keeping only the first
output


In [ ]:
bootfunc = lambda x:test_statistic(x)[0]
with NumpyRNGContext(1):
    bootresult = bootstrap(bootarr, 3, bootfunc=bootfunc)

bootresult  # doctest: +FLOAT_CMP

array([40., 46., 35.])

In [ ]:
bootresult.shape

(3,)