<div class='alert alert-warning'>

# JupyterLite warning

- Running the **scikit-plots 0.5** interactive examples in JupyterLite is experimental and may not always work as expected.
- With high load times especially on low-resource platforms, and the version of scikit-plots might not be in sync with the one you are browsing the documentation for.
- If you encounter any issues, please report them on the [scikit-plots issue tracker](https://github.com/scikit-plots/scikit-plots/issues/new/choose).

```python
# Installing the dependencies first, and then scikit-plots from Anaconda.org.
# Download scikit-plots *pyodide_20XX_0_wasm32.whl
# import micropip
import piplite
await piplite.install(
  'scikit-plots==0.5.dev0',
   index_urls='https://pypi.anaconda.org/scikit-plots-wheels-staging-nightly/simple',
)
import scikitplot as sp; sp.show_versions()
```

</div>

In [ ]:
poisson_conf_interval(np.arange(10), interval='root-n').T

array([[  0.        ,   0.        ],
       [  0.        ,   2.        ],
       [  0.58578644,   3.41421356],
       [  1.26794919,   4.73205081],
       [  2.        ,   6.        ],
       [  2.76393202,   7.23606798],
       [  3.55051026,   8.44948974],
       [  4.35424869,   9.64575131],
       [  5.17157288,  10.82842712],
       [  6.        ,  12.        ]])

In [ ]:
poisson_conf_interval(np.arange(10), interval='root-n-0').T

array([[  0.        ,   1.        ],
       [  0.        ,   2.        ],
       [  0.58578644,   3.41421356],
       [  1.26794919,   4.73205081],
       [  2.        ,   6.        ],
       [  2.76393202,   7.23606798],
       [  3.55051026,   8.44948974],
       [  4.35424869,   9.64575131],
       [  5.17157288,  10.82842712],
       [  6.        ,  12.        ]])

In [ ]:
poisson_conf_interval(np.arange(10), interval='pearson').T

array([[  0.        ,   1.        ],
       [  0.38196601,   2.61803399],
       [  1.        ,   4.        ],
       [  1.69722436,   5.30277564],
       [  2.43844719,   6.56155281],
       [  3.20871215,   7.79128785],
       [  4.        ,   9.        ],
       [  4.8074176 ,  10.1925824 ],
       [  5.62771868,  11.37228132],
       [  6.45861873,  12.54138127]])

In [ ]:
poisson_conf_interval(
    np.arange(10), interval='frequentist-confidence').T

array([[  0.        ,   1.84102165],
       [  0.17275378,   3.29952656],
       [  0.70818544,   4.63785962],
       [  1.36729531,   5.91818583],
       [  2.08566081,   7.16275317],
       [  2.84030886,   8.38247265],
       [  3.62006862,   9.58364155],
       [  4.41852954,  10.77028072],
       [  5.23161394,  11.94514152],
       [  6.05653896,  13.11020414]])

In [ ]:
poisson_conf_interval(
    7, interval='frequentist-confidence').T

array([  4.41852954,  10.77028072])

In [ ]:
poisson_conf_interval(
    10, background=1.5, confidence_level=0.95,
    interval='kraft-burrows-nousek').T  # doctest: +FLOAT_CMP

array([[ 3.47894005, 16.113329533]])