<div class='alert alert-warning'>

scikit-plots's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of scikit-plots might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [scikit-plots issue tracker](https://github.com/scikit-plots/scikit-plots/issues).

</div>

In [ ]:
import numpy as np
from scipy.special import softmax
np.set_printoptions(precision=5)

In [ ]:
x = np.array([[1, 0.5, 0.2, 3], [1, -1, 7, 3], [2, 12, 13, 3]])

Compute the softmax transformation over the entire array.


In [ ]:
m = softmax(x)
m

array([[  4.48309e-06,   2.71913e-06,   2.01438e-06,   3.31258e-05],
       [  4.48309e-06,   6.06720e-07,   1.80861e-03,   3.31258e-05],
       [  1.21863e-05,   2.68421e-01,   7.29644e-01,   3.31258e-05]])

In [ ]:
m.sum()

1.0

Compute the softmax transformation along the first axis (i.e., the
columns).


In [ ]:
m = softmax(x, axis=0)

In [ ]:
m

array([[  2.11942e-01,   1.01300e-05,   2.75394e-06,   3.33333e-01],
       [  2.11942e-01,   2.26030e-06,   2.47262e-03,   3.33333e-01],
       [  5.76117e-01,   9.99988e-01,   9.97525e-01,   3.33333e-01]])

In [ ]:
m.sum(axis=0)

array([ 1.,  1.,  1.,  1.])

Compute the softmax transformation along the second axis (i.e., the rows).


In [ ]:
m = softmax(x, axis=1)
m

array([[  1.05877e-01,   6.42177e-02,   4.75736e-02,   7.82332e-01],
       [  2.42746e-03,   3.28521e-04,   9.79307e-01,   1.79366e-02],
       [  1.22094e-05,   2.68929e-01,   7.31025e-01,   3.31885e-05]])

In [ ]:
m.sum(axis=1)

array([ 1.,  1.,  1.])